package com.anton.web.controller.command;

public enum Message {
    PAGE_ERROR_MESSAGE,
    OPERATION_FAILED,
    OPERATION_SUCCEED,
    WRONG_PASSWORD_OR_USERNAME_OR_EMAIL,
    WRONG_PASSWORD_OR_USERNAME,
    USERNAME_IS_TAKEN,
    USER_NOT_ACTIVE,
    VERIFICATION_SUCCEED,
    VERIFICATION_FAILED,
    EMAIL_SUBJECT,
    EMAIL_MESSAGE
}
