package com.anton.gym.controller.command;

public enum Message {
    INVALID_USERNAME,
    INVALID_PHOTO_REFERENCE,
    INVALID_DESCRIPTION,
    INVALID_USERNAME_AND_DESCRIPTION,
    PAGE_ERROR_MESSAGE,
    OPERATION_FAILED,
    OPERATION_SUCCEED,
    WRONG_PASSWORD_OR_USERNAME_OR_EMAIL,
    WRONG_PASSWORD_OR_USERNAME,
    USERNAME_IS_TAKEN,
    USER_NOT_ACTIVE,
    VERIFICATION_SUCCEED,
    VERIFICATION_FAILED,
    ACCOUNT_ALREADY_ACTIVATED,
    EMAIL_SUBJECT,
    NEW_CLIENT_EMAIL_SUBJECT,
    NEW_CLIENT_EMAIL_MESSAGE,
    EMAIL_MESSAGE,
    ABOUT_ME
}
